export const mockAppInfo = {
  '1': {
    name: '测试应用',
    icon: '🔧',
    description: '用于测试的开发应用',
    appId: 'cli_9a1b2c3d4e5f6',
    appSecret: 'cli_9a1b2c3d4e5f6',
    redirectUrls: 'https://example.com/callback',
    chineseName: '测试应用',
    englishName: 'Test Application',
    chineseDesc: '用于测试的开发应用，提供基础的API接口和事件订阅功能',
    englishDesc: 'A development testing application providing basic API interfaces and event subscription features',
    functionDiagram: '',
    authMethod: 'Cookie',
    eamap: 'EAMAP-2024-001',
  },
  '2': {
    name: '企业服务',
    icon: '🏢',
    description: '企业内部服务平台',
    appId: 'cli_7g8h9i0j1k2l',
    appSecret: 'cli_7g8h9i0j1k2l',
    redirectUrls: 'https://company.com/oauth',
    chineseName: '企业服务',
    englishName: 'Enterprise Service',
    chineseDesc: '企业内部服务平台，整合企业资源，提升协作效率',
    englishDesc: 'Internal enterprise service platform that integrates resources and improves collaboration efficiency',
    functionDiagram: '',
    authMethod: '数字签名',
    eamap: null,
  },
  '3': {
    name: '审批助手',
    icon: '📋',
    description: '企业审批流程管理',
    appId: 'cli_3m4n5o6p7q8r',
    appSecret: 'cli_3m4n5o6p7q8r',
    redirectUrls: 'https://approval.com/callback',
    chineseName: '审批助手',
    englishName: 'Approval Assistant',
    chineseDesc: '企业审批流程管理应用，支持自定义审批流程和多级审核',
    englishDesc: 'Enterprise approval workflow management application with customizable processes and multi-level review',
    functionDiagram: '',
    authMethod: 'SOAHeader',
    eamap: 'EAMAP-2024-002',
  },
};