export const RESOURCE_TYPES = {
  callback: {
    type: 'callback',
    title: '回调',
    labels: {
      nameCn: '回调中文名称',
      nameEn: '回调英文名称',
      permissionNameCn: '权限中文名称',
      permissionNameEn: '权限英文名称',
      scope: 'callback:approval:completed',
    },
    scopePattern: /^callback:[a-zA-Z0-9_-]+:[a-zA-Z0-9_-]+$/,
    scopeMessage: '格式不正确，应为：callback:{模块}:{资源标识}',
    scopeExtra: '格式：callback:{模块}:{资源标识}',
    baseInfoFields: [],
  },
  event: {
    type: 'event',
    title: '事件',
    labels: {
      nameCn: '事件中文名称',
      nameEn: '事件英文名称',
      permissionNameCn: '权限中文名称',
      permissionNameEn: '权限英文名称',
      scope: 'event:im:message-received',
      topic: 'user.status',
    },
    scopePattern: /^event:[a-zA-Z0-9_-]+:[a-zA-Z0-9_-]+$/,
    scopeMessage: '格式不正确，应为：event:{模块}:{事件标识}',
    scopeExtra: '格式：event:{模块}:{事件标识}',
    topicPattern: /^[a-zA-Z][a-zA-Z0-9]*\.[a-zA-Z][a-zA-Z0-9.]*$/,
    topicMessage: '格式不正确，应为：模块.事件',
    topicExtra: '格式：模块.事件，例如：user.status, msg.send.ok',
    baseInfoFields: ['topic'],
  },
  api: {
    type: 'api',
    title: 'API',
    labels: {
      nameCn: 'API中文名称',
      nameEn: 'API英文名称',
      permissionNameCn: '权限中文名称',
      permissionNameEn: '权限英文名称',
      scope: 'api:im:send-message',
    },
    scopePattern: /^api:[a-zA-Z0-9_-]+:[a-zA-Z0-9_-]+$/,
    scopeMessage: '格式不正确，应为：api:{模块}:{资源标识}',
    scopeExtra: '格式：api:{模块}:{资源标识}',
    baseInfoFields: ['path', 'method', 'authType'],
  },
};
