export const mockApis = [
  {
    id: 1,
    name: '获取用户信息',
    scope: 'user.get',
    auth: 'SOA',
    category: '用户管理',
    status: '已审核',
  },
  {
    id: 2,
    name: '发送消息',
    scope: 'message.send',
    auth: 'APIG',
    category: '消息推送',
    status: '审核中',
  },
  {
    id: 3,
    name: '创建日历事件',
    scope: 'calendar.event.create',
    auth: 'APIG',
    category: '日历管理',
    status: '已中止',
  },
  {
    id: 4,
    name: '更新通讯录',
    scope: 'contact.update',
    auth: 'SOA',
    category: '通讯录',
    status: '审核中',
  },
];

export const availableApis = {
  SOA: {
    modules: [
      { key: 'all', name: '所有' },
      { key: 'user', name: '用户管理' },
      { key: 'contact', name: '通讯录' },
      { key: 'department', name: '组织架构' },
    ],
    apis: [
      {
        id: 101,
        name: '获取用户详情',
        scope: 'user.info.get',
        auth: 'SOA',
        category: '用户管理',
        needReview: true,
        docUrl: '/docs/user-info',
      },
      {
        id: 102,
        name: '获取用户列表',
        scope: 'user.list',
        auth: 'SOA',
        category: '用户管理',
        needReview: false,
        docUrl: '/docs/user-list',
      },
      {
        id: 103,
        name: '更新用户信息',
        scope: 'user.update',
        auth: 'SOA',
        category: '用户管理',
        needReview: true,
        docUrl: '/docs/user-update',
      },
      {
        id: 104,
        name: '获取通讯录',
        scope: 'contact.list',
        auth: 'SOA',
        category: '通讯录',
        needReview: false,
        docUrl: '/docs/contact-list',
      },
      {
        id: 105,
        name: '更新通讯录',
        scope: 'contact.update',
        auth: 'SOA',
        category: '通讯录',
        needReview: true,
        docUrl: '/docs/contact-update',
      },
      {
        id: 106,
        name: '获取部门列表',
        scope: 'department.list',
        auth: 'SOA',
        category: '组织架构',
        needReview: false,
        docUrl: '/docs/department-list',
      },
      {
        id: 107,
        name: '获取部门详情',
        scope: 'department.info',
        auth: 'SOA',
        category: '组织架构',
        needReview: true,
        docUrl: '/docs/department-info',
      },
      {
        id: 108,
        name: '创建用户',
        scope: 'user.create',
        auth: 'SOA',
        category: '用户管理',
        needReview: true,
        docUrl: '/docs/user-create',
      },
      {
        id: 109,
        name: '删除用户',
        scope: 'user.delete',
        auth: 'SOA',
        category: '用户管理',
        needReview: true,
        docUrl: '/docs/user-delete',
      },
      {
        id: 110,
        name: '批量获取用户',
        scope: 'user.batch.get',
        auth: 'SOA',
        category: '用户管理',
        needReview: false,
        docUrl: '/docs/user-batch',
      },
      {
        id: 111,
        name: '获取用户头像',
        scope: 'user.avatar.get',
        auth: 'SOA',
        category: '用户管理',
        needReview: false,
        docUrl: '/docs/user-avatar',
      },
      {
        id: 112,
        name: '更新用户头像',
        scope: 'user.avatar.update',
        auth: 'SOA',
        category: '用户管理',
        needReview: true,
        docUrl: '/docs/user-avatar-update',
      },
    ],
  },
  APIG: {
    modules: [
      { key: 'all', name: '所有' },
      { key: 'cloud', name: '云空间' },
      { key: 'meeting', name: '会议管理' },
      { key: 'wechat', name: '公众号' },
      { key: 'message', name: '消息推送' },
    ],
    apis: [
      {
        id: 201,
        name: '获取文件列表',
        scope: 'cloud.file.list',
        auth: 'APIG',
        category: '云空间',
        needReview: false,
        docUrl: '/docs/cloud-file-list',
      },
      {
        id: 202,
        name: '上传文件',
        scope: 'cloud.file.upload',
        auth: 'APIG',
        category: '云空间',
        needReview: true,
        docUrl: '/docs/cloud-file-upload',
      },
      {
        id: 203,
        name: '删除文件',
        scope: 'cloud.file.delete',
        auth: 'APIG',
        category: '云空间',
        needReview: true,
        docUrl: '/docs/cloud-file-delete',
      },
      {
        id: 204,
        name: '创建会议',
        scope: 'meeting.create',
        auth: 'APIG',
        category: '会议管理',
        needReview: true,
        docUrl: '/docs/meeting-create',
      },
      {
        id: 205,
        name: '获取会议列表',
        scope: 'meeting.list',
        auth: 'APIG',
        category: '会议管理',
        needReview: false,
        docUrl: '/docs/meeting-list',
      },
      {
        id: 206,
        name: '取消会议',
        scope: 'meeting.cancel',
        auth: 'APIG',
        category: '会议管理',
        needReview: true,
        docUrl: '/docs/meeting-cancel',
      },
      {
        id: 207,
        name: '获取公众号菜单',
        scope: 'wechat.menu.get',
        auth: 'APIG',
        category: '公众号',
        needReview: false,
        docUrl: '/docs/wechat-menu',
      },
      {
        id: 208,
        name: '发送模板消息',
        scope: 'wechat.template.send',
        auth: 'APIG',
        category: '公众号',
        needReview: true,
        docUrl: '/docs/wechat-template',
      },
      {
        id: 209,
        name: '发送消息',
        scope: 'message.send',
        auth: 'APIG',
        category: '消息推送',
        needReview: true,
        docUrl: '/docs/message-send',
      },
      {
        id: 210,
        name: '发送群消息',
        scope: 'message.group.send',
        auth: 'APIG',
        category: '消息推送',
        needReview: true,
        docUrl: '/docs/message-group',
      },
      {
        id: 211,
        name: '获取文件下载地址',
        scope: 'cloud.file.url',
        auth: 'APIG',
        category: '云空间',
        needReview: false,
        docUrl: '/docs/cloud-file-url',
      },
      {
        id: 212,
        name: '编辑会议',
        scope: 'meeting.update',
        auth: 'APIG',
        category: '会议管理',
        needReview: true,
        docUrl: '/docs/meeting-update',
      },
      {
        id: 213,
        name: '创建云盘文件夹',
        scope: 'cloud.folder.create',
        auth: 'APIG',
        category: '云空间',
        needReview: true,
        docUrl: '/docs/cloud-folder-create',
      },
      {
        id: 214,
        name: '获取会议详情',
        scope: 'meeting.info',
        auth: 'APIG',
        category: '会议管理',
        needReview: false,
        docUrl: '/docs/meeting-info',
      },
    ],
  },
};