export const mockCallbacks = [
  {
    id: '1',
    nameCn: '订单状态回调',
    nameEn: 'Order Status Callback',
    path: '/callback/order',
    categoryId: '3',
    categoryName: '交易服务',
    status: 2,
    permission: {
      nameCn: '订单状态权限',
      scope: 'callback:order:status',
    },
    docUrl: 'https://docs.example.com/callback/order-status',
    createTime: '2026-04-01 10:00:00',
  },
  {
    id: '2',
    nameCn: '支付成功回调',
    nameEn: 'Payment Success Callback',
    path: '/callback/pay',
    categoryId: '3',
    categoryName: '交易服务',
    status: 2,
    permission: {
      nameCn: '支付权限',
      scope: 'callback:payment:success',
    },
    docUrl: 'https://docs.example.com/callback/payment-success',
    createTime: '2026-04-02 10:00:00',
  },
  {
    id: '3',
    nameCn: '用户登录回调',
    nameEn: 'User Login Callback',
    path: '/callback/login',
    categoryId: '3',
    categoryName: '交易服务',
    status: 0,
    permission: {
      nameCn: '登录权限',
      scope: 'callback:user:login',
    },
    docUrl: 'https://docs.example.com/callback/user-login',
    createTime: '2026-04-03 10:00:00',
  },
  {
    id: '4',
    nameCn: '库存变更回调',
    nameEn: 'Inventory Change Callback',
    path: '/callback/inventory',
    categoryId: '3',
    categoryName: '交易服务',
    status: 1,
    permission: {
      nameCn: '库存权限',
      scope: 'callback:inventory:change',
    },
    docUrl: 'https://docs.example.com/callback/inventory-change',
    createTime: '2026-04-04 10:00:00',
  },
  {
    id: '5',
    nameCn: '物流状态回调',
    nameEn: 'Shipping Status Callback',
    path: '/callback/shipping',
    categoryId: '3',
    categoryName: '交易服务',
    status: 3,
    permission: {
      nameCn: '物流权限',
      scope: 'callback:shipping:status',
    },
    docUrl: 'https://docs.example.com/callback/shipping-status',
    createTime: '2026-04-05 10:00:00',
  },
];