export const mockEvents = [
  {
    id: '1',
    nameCn: '用户状态变更',
    nameEn: 'User Status Change',
    topic: 'user.status',
    categoryId: '2-1',
    categoryName: '用户状态变更',
    status: 2,
    permission: {
      nameCn: '用户状态权限',
      scope: 'event:user:status',
    },
    docUrl: 'https://docs.example.com/event/user-status',
    createTime: '2026-04-01 10:00:00',
  },
  {
    id: '2',
    nameCn: '消息发送成功',
    nameEn: 'Message Send Success',
    topic: 'msg.send.ok',
    categoryId: '1-2',
    categoryName: '消息推送',
    status: 2,
    permission: {
      nameCn: '消息发送权限',
      scope: 'event:msg:send',
    },
    docUrl: 'https://docs.example.com/event/msg-send',
    createTime: '2026-04-02 10:00:00',
  },
  {
    id: '3',
    nameCn: '新用户注册',
    nameEn: 'New User Register',
    topic: 'user.register',
    categoryId: '2-1',
    categoryName: '用户状态变更',
    status: 0,
    permission: {
      nameCn: '注册权限',
      scope: 'event:user:register',
    },
    docUrl: 'https://docs.example.com/event/user-register',
    createTime: '2026-04-03 10:00:00',
  },
  {
    id: '4',
    nameCn: '订单创建事件',
    nameEn: 'Order Created Event',
    topic: 'order.created',
    categoryId: '2-1',
    categoryName: '用户状态变更',
    status: 1,
    permission: {
      nameCn: '订单权限',
      scope: 'event:order:created',
    },
    docUrl: 'https://docs.example.com/event/order-created',
    createTime: '2026-04-04 10:00:00',
  },
  {
    id: '5',
    nameCn: '支付完成事件',
    nameEn: 'Payment Completed Event',
    topic: 'payment.completed',
    categoryId: '1-2',
    categoryName: '消息推送',
    status: 3,
    permission: {
      nameCn: '支付权限',
      scope: 'event:payment:completed',
    },
    docUrl: 'https://docs.example.com/event/payment-completed',
    createTime: '2026-04-05 10:00:00',
  },
];